### ISSUE TITLE
БОльшая часть сенсоров недоступна

### ISSUE THREAD

**Issue by alting** [alryaz/hass-pandora-cas#1]
В логах:
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 335, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 454, in async_device_update
    await self.async_update()  # type: ignore
  File "/home/homeassistant/.homeassistant/custom_components/pandora_cas/__init__.py", line 660, in async_update
    value = getattr(self._device, config[ATTR_ATTRIBUTE])
  File "/home/homeassistant/.homeassistant/custom_components/pandora_cas/api.py", line 659, in status
    self._bit_status = BitStatus(self._stats['bit_state_1'])
  File "/usr/local/lib/python3.8/enum.py", line 309, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 600, in __new__
    raise exc
  File "/usr/local/lib/python3.8/enum.py", line 584, in __new__
    result = cls._missing_(value)
  File "/usr/local/lib/python3.8/enum.py", line 793, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: '2305843009213694337' is not a valid BitStatus
2020-09-13 16:18:05 ERROR (MainThread) [homeassistant.components.binary_sensor] pandora_cas: Error on device update!
ValueError: '2305843009213694337' is not a valid BitStatus

**Comment by alryaz** [comment]
Да, действительно, у Вас устройство отдаёт интересный статус.
Поправлю, чтобы ошибки не было, но всё же хотелось бы связаться с Вами через Telegram/E-mail, чтобы разобраться, имеются ли для Вашего устройства какие-нибудь дополнительные фишки.

**Comment by alryaz** [comment]
Попробуйте переключиться на ветку `master`, на ней выпустил фикс. Если у Вас заработает, неменого получше оформлю, и вылью в релиз.

**Comment by alting** [comment]
А каким образом можно выбрать ветку в штатной интеграции HA?

**Comment by alryaz** [comment]
В HACS на компоненте три точки, "Update information"/"Reload information", затем те же три точки, и "Reinstall"; ветка должна быть в списке (`master`).

**Comment by alting** [comment]
стало получше... 
появились датчики открытия/закрытия дверей, капота, багажника
по-прежнему недоступны датчики температуры, скорости, пробега, состояния сигнализации (машина открыта/закрыта), работы двигателя, скорости движения

**Comment by alryaz** [comment]
Запушил пару изменений в механизме фильтрации доступных возможностей устройств, попробуйте сейчас.

Edit: Ошибочно запушил не верные правки.

**Comment by alting** [comment]
Все осталось по-прежнему

Нет, вру. Что-то поменялось. Появились новые сущности, которых не было в прежней интеграции.
по-прежнему недоступна температура, состояние и обороты двигателя, скорость и состояние покой/движение

**Comment by alryaz** [comment]
А вот тут уже ошибка, которая тянется на всех моих компонентах, которую я "за кулисами" пытаюсь починить (к версии v0.1.0).

В README немного нечестные defaults для платформ, поэтому для активации упомянутых Вами сенсоров/свичей/итд потребуется в YAML написать `sensor: true` и т.д., [Раздел README](https://github.com/alryaz/hass-pandora-cas#%D0%B4%D0%BE%D0%BF%D0%BE%D0%BB%D0%BD%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%BA%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D1%8F-%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BF%D0%BB%D0%B0%D1%82%D1%84%D0%BE%D1%80%D0%BC)

Edit: альтернативно включить их можно через GUI в разделе "Настройки" &#10230; "Интеграции" &#10230; "Pandora Car Alarm System" &#10230; нажать на "28 объектов" (может быть не 28, привожу в пример) &#10230; выставить переключатель "отображать объект" в положение "вкл." &#10230; нажать "обновить"

**Comment by alting** [comment]
Магия... Действительно, отобразил скрытые объекты и вижу теперь их состояние.

И, мне кажется, не отрабатывают состояния... 
Например, открытия/закрытия двери.. 
Надо спуститься к машине - проверить.

**Comment by alryaz** [comment]
Проверил только что, отрабатывают (но, естественно, с задержкой ввиду интервального обновления)

Вы можете уменьшить интервал опроса (=увеличить количество опросов), чтобы получать актуальное состояние чаще.

**Comment by alting** [comment]
Открытие/закрытие дверей не отрабатывает совсем. Движение - тоже. Хотя скорость показывает.
Понаблюдаю еще.

**Comment by alryaz** [comment]
В приложении Pandora Online показывает факт открытия дверей?

**Comment by alting** [comment]
Да. Жена ездила, открыл приложение и HA. В приложении показывает, в HA молчок. Сделал автоматизацию об оповещении открытия/закрытия водительской двери - молчок.
polling_interval: 40
Может, не успевает просто.
Но в старой интеграции четко отслеживало.

**Comment by alryaz** [comment]
Приложение обновляется немного иначе, чем компонент.
К сожалению, ввиду того, как приложение работает с сервером, тяжело реализовать протокол обмена данными, который был бы удобен в настройке конечным пользователем.

В приложении обновления приходят моментально с сервера; на сайте обновления приходят примерно так же, как и в компоненте.

Вы можете поставить `polling_interval` в предельное значение, коим является 15 (секунд). Эти запросы, как я понял, пеленгуют сервер Pandora, но не саму сигнализацию, а, следовательно, кушать трафик встроенной сим-карты частые запросы не должны.

Прошу не брать мои слова за гарант, так как проект разрабатывается без наличия какой-либо официальной документации.

Edit: вопрос я закрываю, однако параллельно постараюсь реализовать механизм работы а-ля приложение. Вынужден упомянуть, что настройка будет экспертной, и задействует множество сторонних ресурсов.

**Comment by alting** [comment]
Да. Спасибо большое за разъяснения и за интеграцию!
