### ISSUE TITLE
Я не понял одно магическое значение, и откуда оно появилось

### ISSUE THREAD

**Issue by ragnaros12** [alryaz/hass-pandora-cas#11]
В общем мне довольно интересен проект, и в исходниках api я нашел вот эту строчку
"Authorization": "Basic cGNvbm5lY3Q6SW5mXzRlUm05X2ZfaEhnVl9zNg=="
И мне не совсем понятно что за магическое значение, и откуда можно взять похожее) Объясните пожалуйста

**Comment by alryaz** [comment]
Авторизация на сервере Pandora. Такое же значение использует мобильное приложение, насколько мне известно.

В теории, возможно найти (или запросить) другое значение, однако пока что прецедентов не было.

**Comment by ragnaros12** [comment]
Спасибо большое за пояснение)
