### ISSUE TITLE
About pandora api

### ISSUE THREAD

**Issue by ragnaros12** [alryaz/hass-pandora-cas#12]
Is there any documentation somewhere, or maybe you can get some information from you on how to properly get a list of devices and data from them. Because I don't really understand python, and it's quite difficult to understand what's what

**Comment by alryaz** [comment]
Unfortunately, there is no official documentation available (at least not publicly, as of 2021; that's the year I last searched for it).

The included API file (soon to be moved to a separate Python package) may provide an overview on how stuff is requested; however, as you've stated that you are not fluent in Python, you might wish to take a look at HTTP requests in your browser's developer tools when using the official website (https://pro.p-on.ru/). That does, however, require you to be logged in.

Edit: upon moving the API to a separate package, documentation will be improved.

Edit 2: you might be willing to contact Alarmtrade directly for implementation as I'm confident they offer documentation and reference implementations for large-scale business applications.
