### ISSUE TITLE
Ошибка при работе с маяком Pandora

### ISSUE THREAD

**Issue by vladtechno** [alryaz/hass-pandora-cas#13]
Добрый день. Использую связку сигнализация + маяк NAV-08. Определяет все хорошо, два устройства появляются в интеграции. Ошибка происходит создании выключателей сигнализации. Ошибка:
`Logger: homeassistant.components.switch
Source: custom_components/pandora_cas/__init__.py:683
Integration: Выключатель ([documentation](https://www.home-assistant.io/integrations/switch), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+switch%22))
First occurred: 11 ноября 2022 г., 21:59:59 (1 occurrences)
Last logged: 11 ноября 2022 г., 21:59:59
Error while setting up pandora_cas platform for switch

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/pandora_cas/__init__.py", line 683, in async_platform_setup_entry
    and not entity_config[ATTR_FEATURE] & device.features
TypeError: unsupported operand type(s) for &: 'Features' and 'NoneType'`

Если маяк удалить, все без ошибок, выключатели создаются.

**Comment by alryaz** [comment]
В грядущем обновлении features теперь несут "рекомендательный" характер (в том плане, что объекты будут попросту выключены, но не недоступны). На ветке master последние изменения.

**Comment by alryaz** [comment]
Закрыто в обновлениях v2023.6.*
