### ISSUE TITLE
Ошибка при загрузке данных по транспортному средству. 

### ISSUE THREAD

**Issue by diemon24** [alryaz/hass-pandora-cas#14]
Logger: custom_components.pandora_cas.api
Source: custom_components/pandora_cas/api.py:1248 
Integration: Pandora Car Alarm System (documentation, issues) 
First occurred: 01:28:06 (1 occurrences) 
Last logged: 01:28:06

Error during preliminary response processing with message type initial-state: KeyError('id') Please, report this error to the developer immediately!

Logger: custom_components.pandora_cas.api
Source: custom_components/pandora_cas/api.py:1194 
Integration: Pandora Car Alarm System (documentation, issues) 
First occurred: 01:28:07 (6 occurrences) 
Last logged: 01:31:15

Device with ID '1077463177' partial state data retrieved, but no initial data has yet been received. Skipping...

Данные по 1 транспортному средству загружаются корректно, по второму - перестали загружаться 22.11. До этого работало все корректно. 

<img width="506" alt="image" src="https://user-images.githubusercontent.com/91910101/203435147-834cc9f0-734b-4adb-a475-da552bf5e868.png">

**Comment by saraykina** [comment]
аналогичная проблема, возникла после обновления HA на 2022.11.4

**Comment by diemon24** [comment]
> аналогичная проблема, возникла после обновления HA на 2022.11.4

Думаю не связано с обновлением, у меня версия ХА 2022.11.2, Frontend 2221108.0

**Comment by org1org** [comment]
Аналогично, но я только поставил интеграцию, ХА обновлен до последней версии
Device with ID 'xxxxxxxxxxxx' partial state data retrieved, but no initial data has yet been received. Skipping...
Соседняя интеграция от turbulator'а, кстати, работает

**Comment by diemon24** [comment]
> Аналогично, но я только поставил интеграцию, ХА обновлен до последней версии
> Device with ID 'xxxxxxxxxxxx' partial state data retrieved, but no initial data has yet been received. Skipping...
> Соседняя интеграция от turbulator'а, кстати, работает

А что за интеграция? Можно ссылку плс

**Comment by org1org** [comment]
> А что за интеграция? Можно ссылку плс

https://github.com/turbulator/pandora-cas

**Comment by diemon24** [comment]
> > А что за интеграция? Можно ссылку плс
> 
> https://github.com/turbulator/pandora-cas

Спасибо. Попробую ее.

**Comment by diemon24** [comment]
> > > А что за интеграция? Можно ссылку плс
> > 
> > 
> > https://github.com/turbulator/pandora-cas
> 
> Спасибо. Попробую ее.

Жаль, в ней не все сенсоры подтягиваются... Например статуса зажигания нет, только RPM, нет сенсора device_tracker отсутствует, хотя в описании заявлен, а в таблице сенсоров и состояний в описании даже не описан.

**Comment by diemon24** [comment]
Проблема так и не ушла.
Я попытался исправить проблему: у меня две машины было заведены через одну УЗ p-on через делегирование прав на авто. Я подключил для теста прямые УЗ с полными правами на авто. Один и тот же автомобиль не подгружает данные. Что очень странно. Такое ощущение, что обновился токен подключения именно к данному автомобилю. 

Эта ошибка возникла в кастомной интеграции.

Logger: custom_components.pandora_cas.api
Source: custom_components/pandora_cas/api.py:1194 
Integration: Pandora Car Alarm System (documentation, issues) 
First occurred: 17:10:43 (1 occurrences) 
Last logged: 17:10:43

Device with ID 'MY_ID' partial state data retrieved, but no initial data has yet been received. Skipping...

<img width="769" alt="image" src="https://user-images.githubusercontent.com/91910101/204298842-79be1f30-4abc-446c-8124-9fdc678a7250.png">

<img width="532" alt="image" src="https://user-images.githubusercontent.com/91910101/204298899-667f601b-cad9-43e9-b33a-be2ae37bfe22.png">

<img width="300" alt="image" src="https://user-images.githubusercontent.com/91910101/204299031-04d77007-18e1-4324-b3f7-d9f008ba408e.png">

@alryaz Подскажите в чем может быть дело? Не залочили ли API со стороны сервиса (например по причине частых запросов)?

**Comment by Zhel2** [comment]
Тоже не работает. Сначала грешил на обновление ха, но потом откатился на старый бэкап - то же самое. По логам больше похоже на ошибку авторизации, но при настройке интеграции на логин и пароль не ругается.

**Comment by evsmorodin** [comment]
Там ошибка подключения к вебсокету, скорее всего изменилась логика работы. Я бы сделал исправления и предложил смержиться, но я в питоне не бум-бум совсем ) Да и по-хорошему надо бы знать как оно было до этого, чтобы понимать, что изменилось. В браузере проверил: зашёл на сайт, в расширении для проверки вебсокетов подключился без проблем, причём без использования токена, есть подозрение, что сессия юзера теперь берется из кук

**Comment by diemon24** [comment]
> Там ошибка подключения к вебсокету, скорее всего изменилась логика работы. Я бы сделал исправления и предложил смержиться, но я в питоне не бум-бум совсем ) Да и по-хорошему надо бы знать как оно было до этого, чтобы понимать, что изменилось. В браузере проверил: зашёл на сайт, в расширении для проверки вебсокетов подключился без проблем, причём без использования токена, есть подозрение, что сессия юзера теперь берется из кук

Так вот что странно - 1 машина подключается и показывают сенсоры, вторая - нет. Ранее я подключал обе машины через выделенную УЗ, которой авто подключены без возможности управления через делегирование прав. Но попробовал подключить родительские УЗ от двух авто, и та же самая история - 1 та же самая авто не показывает ничего, вторая показывает. 

Т.е. проблема не Кук, потому что я подключаюсь к двум авто либо из одной УЗ, в которой все работало, либо из двух разных, но одна как работала, так и продолжает работать. Ощущение, что именно по конкретным авто что-то залочилось…

**Comment by Zhel2** [comment]
Ну так перестал работать только этот этот форк. Основная интеграция работает без проблем.
https://community.home-assistant.io/t/pandora-car-alarm-system-custom-component/117125/154

**Comment by Zhel2** [comment]
Мне этот форк нравился тем что есть отдельные объекты switch engine и lock, а также больше сенсоров, например мне нужен brake

**Comment by alryaz** [comment]
`v2.0.1` выпущена. Прошу протестировать. (от некоторых пользователей работоспособность уже подтверждена)

Оказывается, не всем отдаётся ключ `id` в JSON (мне, например, отдаётся).

В грядущем релизе буду добавлять новые атрибуты из API.

**Comment by Zhel2** [comment]
[alryaz](https://github.com/alryaz) лучший! Я тоже проверил - все работает.

**Comment by diemon24** [comment]
> `v2.0.1` выпущена. Прошу протестировать. (от некоторых пользователей работоспособность уже подтверждена)
> 
> Оказывается, не всем отдаётся ключ `id` в JSON (мне, например, отдаётся).
> 
> В грядущем релизе буду добавлять новые атрибуты из API.

Супер! Работает, спасибо!!

**Comment by diemon24** [comment]
Кстати, могу поделиться своей поделкой карточек без кнопок управления, кому интересно: 

![image](https://user-images.githubusercontent.com/91910101/204626207-700b5f69-03ee-4741-9d89-67d52f4862c3.png)

**Comment by org1org** [comment]
> Кстати, могу поделиться своей поделкой карточек без кнопок управления, кому интересно:
> 

Поделитесь, пожалуйста

**Comment by evsmorodin** [comment]
Запрос с карточками оформил отдельно, предлагаю продолжить там
