### ISSUE TITLE
Проблема с треккером устройства

### ISSUE THREAD

**Issue by Shemmmy** [alryaz/hass-pandora-cas#16]
Привет!
Заметил, что периодически треккер начинает дурить - график устройства нормально двигается по оси (х), а по оси (у) скачет ступеньками. При этом отображение маршрута на сайте пандоры абсолютно нормальное.

HA 2022.11.5
компонент 2.0.1, замечено было еще на 2.0.0
![cas - gps](https://user-images.githubusercontent.com/66095040/204996547-7b8a767b-5d3e-4818-b4a1-2a35ac6d6f80.JPG)

**Comment by Shemmmy** [comment]
Кто-то скажет что проблема не интеграции, а с треккерами глобально, но нет: вот вам сборный скриншот. На нем синий и фиолетовый маршруты должны совпадать.
![photo_2022-12-02_16-26-26](https://user-images.githubusercontent.com/66095040/205305643-32a1e081-a557-49f6-a3c8-48c3a92adcd9.jpg)

**Comment by Shemmmy** [comment]
И вновь рубрика "о наболевшем"
![cas - gps1](https://user-images.githubusercontent.com/66095040/206975712-530c9579-b747-434b-9e1d-2fc236a8b0e8.JPG)
![cas - gps1 - p-on](https://user-images.githubusercontent.com/66095040/206975734-fa235b55-8a10-488c-9428-87d1dad97719.JPG)

**Comment by Zhel2** [comment]
Могу предположить что дело в частоте опроса состояния сигнализации. В этой интеграции оно достаточно большое  В альтернативной интеграции Pandora частоту опроса можно задать в настройках произвольно. Но мне эта интеграция больше нравиться. Просим автора добавить аналогичную фичу.

**Comment by Shemmmy** [comment]
Привет!
Не думаю, что проблема связана с частотой опроса - точки появляются. а вот с обработкой данных явно косяк - явные проблемы то с горизонтальными то с вертикальными координатами.

**Comment by Zhel2** [comment]
Да.  потдверждаю координаты интергацией обрабатываются неправильно

**Comment by Zhel2** [comment]
Удалось ли найти причину неправильного  отображения координат?

**Comment by alryaz** [comment]
Полагаю, что лестницы в последней версии компонента должны пропасть.

Так и не удалось найти конкретную причину, однако ближайшее предположение - троттлинг обновления данных объекта.

Сейчас объект трекера обновляется иным образом; за неделю тестирования лестниц (за исключением в районах с невероятно слабым GPS; там не _лестницы_, там _перелёты_) не было замечено.

**Comment by alryaz** [comment]
Лестницы 100% исправлены в 2023.6.*.

Виной всему был запрограммированный мною неправильно алгоритм сглаживания. Совершенно случайно наткнулся.

≤2.0.1 – сглаживание отдельно по каждой координате
≤2023.6.8 – земля плоская, дистанция между координатами ≥0.0001 для изменений
≥2023.6.9 – земля круглая, дистанция между координатами по сфере ≥10м (вскоре будет настраиваемой)
