### ISSUE TITLE
В карточке default.yaml некорректно отображается состояние центрального замка

### ISSUE THREAD

**Issue by Sellec** [alryaz/hass-pandora-cas#17]
[hass-pandora-cas](https://github.com/alryaz/hass-pandora-cas)/[interface](https://github.com/alryaz/hass-pandora-cas/tree/master/interface)/[cards](https://github.com/alryaz/hass-pandora-cas/tree/master/interface/cards)/default.yaml
В самом конце:

> elements:
>   - conditions:
>     - entity: lock.REPLACE_WITH_PANDORA_ID_active_security
>       state: 'on'
>     elements:
>     - entity: lock.REPLACE_WITH_PANDORA_ID_active_security
>       image: data:image/webp;base64,...
>       style:
>         filter: none
>         height: 20.308%
>         left: 54.665%
>         top: 37.692%
>         transform: none
>         width: 13.172%
>       type: image
>     type: conditional
>   - conditions:
>     - entity: lock.REPLACE_WITH_PANDORA_ID_active_security
>       state_not: 'on'
>     elements:
>     - conditions:
>       - entity: lock.REPLACE_WITH_PANDORA_ID_central_lock
>         **_state_**: unlocked
>       elements:
>       - entity: lock.REPLACE_WITH_PANDORA_ID_central_lock
>         image: data:image/webp;base64,...
>         style:
>           filter: none
>           height: 20.308%
>           left: 54.995%
>           top: 37.692%
>           transform: none
>           width: 12.623%
>         type: image
>       type: conditional
>     - conditions:
>       - entity: lock.REPLACE_WITH_PANDORA_ID_central_lock
>         **_state_not_**: unlocked
>       elements:
>       - entity: lock.REPLACE_WITH_PANDORA_ID_central_lock
>         image: data:image/webp;base64,...
>         style:
>           filter: none
>           height: 20.308%
>           left: 49.726%
>           top: 37.692%
>           transform: none
>           width: 23.271%
>         type: image
>       type: conditional
>     type: conditional
>   type: conditional
> image: data:image/webp;base64,...
> type: picture-elements

Выделенные элементы state_not и state надо поменять местами, так как замок в закрытом состоянии отображается как открытый и наоборот.

**Comment by alryaz** [comment]
Исправлено в последнем коммите

Спасибо, что обнаружили, @Sellec !
