### ISSUE TITLE
Ошибка при настройке

### ISSUE THREAD

**Issue by 4tomson** [alryaz/hass-pandora-cas#22]
### Следующие действия были мною выполнены перед созданием обращения

- [X] **Успешный вход в мобильное приложение Pandora Connect / Pandora Online.**  
Successful authentication with Pandora Connect / Pandora Online smartphone app.

- [X] **Успешный вход на сайт https://pro.p-on.ru или https://p-on.ru.**  
Successful authentication with web portal.

- [X] **Отсутствуют явные упоминания о несовместимости устройства в README-файле.**  
Any discrete mentions of incompatibility of device missing from README.

- [X] **Смежные обращения по проблеме _отсутствуют_.**  
There are _no issues_ describing similar problem.

- [ ] **Лог-файлы интеграции загружены на Pastebin или скопированы в поле ниже.**  
Integration log files uploaded to Pastebin or pasted into the field below.

### Версия интеграции / Integration version

2023.7.15

### Версия Home Assistant / Home Assistant version

2023.7.2

### Способ установки Home Assistant / Home Assistant install method

Supervised

### Способ установки интеграции / Integration install method

HACS (Home Assistant Community Store)

### Модель устройства / Device model

Dxl 3940

### Описание проблемы / Problem description

При попытке вести логин пароль ошибка
User input malformed: expected dict for dictionary value @ data['effective_read_timeout']

Переустановил, пробовал разные аккаунты

### Способ воспроизведения / Steps to reproduce

```bash
1.
2.
3.
...
```

**Comment by DefendTS** [comment]
У меня то же самое, и при настройке   через интерфейс и через YAML. Проблема началась после обновления.

**Comment by alryaz** [comment]
Отсутствуют

**Comment by alryaz** [comment]
Отсутствуют логи и верная версия интеграции (7.15 - такой нет). Пожалуйста, добавьте.

**Comment by 4tomson** [comment]
Версия последняя, 7.9 наверное. В общем, последняя.
А какие могут быть логи? Он же прямо при проверке говорит о какой то ошибке, как будто требования не соблюдены.
В логах ничего нету

User input malformed: expected dict for dictionary value @ data['effective_read_timeout'

**Comment by alryaz** [comment]
Попробуйте версию v2023.7.11, ошибка может быть исправлена.

**Comment by 4tomson** [comment]
К сожалению, нет.
Что это за effective_read_timeout?

Вот так если текстом писать
The system cannot restart because the configuration is not valid: Invalid config for [pandora_cas]: expected dict for dictionary value @ data['pandora_cas'][0]['effective_read_timeout']. Got None expected dict for dictionary value @ data['pandora_cas'][0]['polling_interval']. Got None. (See /config/configuration.yaml, line 98).

**Comment by alryaz** [comment]
~~А, YAML-конфигурация. Понятно. Вскоре запушу новое.~~
Попробовал воспроизвести, не произошло.

Попробую исправить завтра утром изменя настройку параметра.

**Comment by DefendTS** [comment]
Если при настройке менять время опроса, то сообщение меняется на Unknown error occurred

**Comment by DefendTS** [comment]
И четвертый чекбокс при настройке через интерфейс без текста.

**Comment by 4tomson** [comment]
> ~А, YAML-конфигурация. Понятно. Вскоре запушу новое.~ Попробовал воспроизвести, не произошло.
> 
> Попробую исправить завтра утром изменя настройку параметра.

Это при любом варианте настройки появляется.
То есть, и так, и так пробую.
Началось именно после обновления

**Comment by 4tomson** [comment]
Тоже 4й чекбокс без текста, тоже ошибка если менять время опроса сначала как у коллеги, а теперь вот такая:
Invalid flow specified

**Comment by 4tomson** [comment]
Попробуйте чтобы воспроизвести проблему, все удалить, установить интеграцию заново и при настройке ввести только имя пользователя и пароль, больше ничего

**Comment by DefendTS** [comment]
Я все удалял и ставил заново, переустанавливать. При Настройке через интерфейс и через yaml. Результат не меняется. Версия 7.9, ставил первую какую выдавал hacs (7.3 или 7.2).
Проблема началась когда обновился предыдуей версии обновился, написало ошибка миграции, а затем после переустановки результат что выше.

**Comment by 4tomson** [comment]
У меня всё ровно то же самое. Ошибка миграции и более не могу настроить

**Comment by alryaz** [comment]
Проблему удалось воспроизвести. Выложил обновление v2023.7.12.

**Comment by DefendTS** [comment]
У меня все заработало.

**Comment by DefendTS** [comment]
Спасибо!

**Comment by 4tomson** [comment]
У меня тоже, спасибо!
