### ISSUE TITLE
Ошибка миграции

### ISSUE THREAD

**Issue by sankey-1** [alryaz/hass-pandora-cas#24]
### Следующие действия были мною выполнены перед созданием обращения

- [X] **Успешный вход в мобильное приложение Pandora Connect / Pandora Online.**  
Successful authentication with Pandora Connect / Pandora Online smartphone app.

- [X] **Успешный вход на сайт https://pro.p-on.ru или https://p-on.ru.**  
Successful authentication with web portal.

- [X] **Отсутствуют явные упоминания о несовместимости устройства в README-файле.**  
Any discrete mentions of incompatibility of device missing from README.

- [X] **Смежные обращения по проблеме _отсутствуют_.**  
There are _no issues_ describing similar problem.

- [X] **Лог-файлы интеграции загружены на Pastebin или скопированы в поле ниже.**  
Integration log files uploaded to Pastebin or pasted into the field below.

### Версия интеграции / Integration version

v2023.7.12

### Версия Home Assistant / Home Assistant version

v2023.7.3

### Способ установки интеграции / Integration install method

HACS (Home Assistant Community Store)

### Модель устройства / Device model

Pandora DX4G

### Описание проблемы / Problem description

Перестала работать интеграция. В какой именно момент сказать не могу, так как последнее время ей не пользовался, к сожалению.

### Способ воспроизведения / Steps to reproduce

Интеграция не работает совсем

### Ожидаемый результат / Expected outcome

нечего написать

### Журнал отладки и сообщения об ошибках / Traceback and logging information

Эта ошибка возникла в пользовательской интеграции.

Logger: homeassistant.config_entries
Source: custom_components/pandora_cas/__init__.py:531 
Integration: Pandora Car Alarm System (documentation, issues) 
First occurred: 28 июля 2023 г. в 20:22:29 (2 occurrences) 
Last logged: 28 июля 2023 г. в 20:22:29

Error migrating entry 1076945725 for pandora_cas
Error migrating entry 1078306444 for pandora_cas
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pandora_cas/__init__.py", line 531, in async_migrate_entry
    hass, verify_ssl=new_options[CONF_VERIFY_SSL]
                     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'verify_ssl'


### Дополнительные сведения / Additional context

_No response_

**Comment by alryaz** [comment]
Здравствуйте, @sankey-1 ! Попробуйте установить предрелиз v2023.7.13.

Спасибо Вам за оставленное обращение!

**Comment by Gusev-Alex** [comment]
> Здравствуйте, @sankey-1 ! Попробуйте установить предрелиз v2023.7.13.
> 
> Спасибо Вам за оставленное обращение!

Мне помогло, спасибо
