### ISSUE TITLE
Аутентификационные данные в коде

### ISSUE THREAD

**Issue by gallyamb** [alryaz/hass-pandora-cas#25]
### Следующие действия были мною выполнены перед созданием обращения

- [X] **Успешный вход в мобильное приложение Pandora Connect / Pandora Online.**  
Successful authentication with Pandora Connect / Pandora Online smartphone app.

- [X] **Успешный вход на сайт https://pro.p-on.ru или https://p-on.ru.**  
Successful authentication with web portal.

- [X] **Отсутствуют явные упоминания о несовместимости устройства в README-файле.**  
Any discrete mentions of incompatibility of device missing from README.

- [X] **Смежные обращения по проблеме _отсутствуют_.**  
There are _no issues_ describing similar problem.

- [X] **Лог-файлы интеграции загружены на Pastebin или скопированы в поле ниже.**  
Integration log files uploaded to Pastebin or pasted into the field below.

### Версия интеграции / Integration version

master

### Версия Home Assistant / Home Assistant version

master

### Способ установки интеграции / Integration install method

HACS (Home Assistant Community Store)

### Модель устройства / Device model

Any

### Описание проблемы / Problem description

https://github.com/alryaz/hass-pandora-cas/blob/bc0e938a3a71c70916fe504f642f8934efce3d33/custom_components/pandora_cas/api.py#L1015

### Способ воспроизведения / Steps to reproduce

-

### Ожидаемый результат / Expected outcome

Аутентификационные данные передаются извне

**Comment by gallyamb** [comment]
Привет! Набрёл на репу в поисках информации для интеграции с Алисой. Не уверен, действительно ли это проблема, но на всякий случай

**Comment by alryaz** [comment]
Эти данные – аутентификационный токен приложения, взятый из онлайна.
Токен не является частью пользовательской авторизации и лишь идентифицирует источник вызовов к API. Токены пользовательской авторизации не защити (см. API.py, будет вынесен в библиотеку).

Сам токен (далее не уверен) не менялся уже давно и используется (по словам знакомых) в новых приложениях. Использование собственных токенов не предусмотрено (добавить эту возможность можно, но практического применения пока что нет).

*P.S. Согласен, иметь авторизацию в коде – плохо. Но это меньшая из зол, если речь идёт об удобстве использования и настройки. Если будет замечено, что токен изменится, обязательно добавлю возможность менять его из интерфейса HA.*
