### ISSUE TITLE
Проблема с координатами

### ISSUE THREAD

**Issue by remezen** [alryaz/hass-pandora-cas#30]
### Следующие действия были мною выполнены перед созданием обращения

- [X] **Успешный вход в мобильное приложение Pandora Connect / Pandora Online.**  
Successful authentication with Pandora Connect / Pandora Online smartphone app.

- [X] **Успешный вход на сайт https://pro.p-on.ru или https://p-on.ru.**  
Successful authentication with web portal.

- [X] **Отсутствуют явные упоминания о несовместимости устройства в README-файле.**  
Any discrete mentions of incompatibility of device missing from README.

- [X] **Смежные обращения по проблеме _отсутствуют_.**  
There are _no issues_ describing similar problem.

- [x] **Лог-файлы интеграции загружены на Pastebin или скопированы в поле ниже.**  
Integration log files uploaded to Pastebin or pasted into the field below.

### Версия интеграции / Integration version

v2024.3.9

### Версия Home Assistant / Home Assistant version

v2024.3.3

### Способ установки интеграции / Integration install method

HACS (Home Assistant Community Store)

### Модель устройства / Device model

Pandora VX-4G (DX4GA)

### Описание проблемы / Problem description

После последних обновлений начались проблемы с координатами.
Причем очень интересным образом - дополнение получает только одну координату.
![Screenshot_20240326_171846_Chrome](https://github.com/alryaz/hass-pandora-cas/assets/2427989/ca3d32c9-38fa-4f5c-af01-d16956bbb7ac)

### Способ воспроизведения / Steps to reproduce

Периодическое или ручное обновление

### Ожидаемый результат / Expected outcome

Отсутствие такого поведения

**Comment by alryaz** [comment]
Здравствуйте! Напишите мне в ЛС. Необходимы журналы (содержат конфиденциальную информацию; не публикуйте её здесь, не очистив лог).

**Comment by remezen** [comment]
Добрый день!
Можете объяснить что нужно сделать?

**Comment by alryaz** [comment]
Напишите в группу: https://t.me/alryaz_ha_addons

**Comment by remezen** [comment]
Исправлено в 2024.3.10, спасибо!

**Comment by remezen** [comment]
Исправлено в 2024.3.10, спасибо!

**Comment by remezen** [comment]
Исправлено в 2024.3.10, спасибо!
