### ISSUE TITLE
platform sensor is not work

### ISSUE THREAD

**Issue by ipmerlin** [alryaz/hass-pandora-cas#4]
![image](https://user-images.githubusercontent.com/35879628/128404629-8c70be26-d849-42a4-86e2-ca67bca7f7de.png)
platform sensor is not work

**Comment by alryaz** [comment]
Объект может быть выключен в HA; нажмите на него (на странице со скрина), и переключите выключатель в активное положение.

Иначе, напишите в Telegram: @alryaz, разберёмся.

**Comment by Keles75** [comment]
In last release core/homeassistant/const.py I found some changes:
Was:
# Voltage units
VOLT: Final = "V"
Now:
# Electric_potential units
ELECTRIC_POTENTIAL_MILLIVOLT: Final = "mV"
ELECTRIC_POTENTIAL_VOLT: Final = "V"

Need to change VOLT to ELECTRIC_POTENTIAL_VOLT in the sensors.py

**Comment by alryaz** [comment]
@Keles75, thank you for your contribution! Will test today (albeit I don't have any device available), and will fix.

**Comment by alryaz** [comment]
Fixed in v0.0.6
