### ISSUE TITLE
Добавить в список рабочих устройство.

### ISSUE THREAD

**Issue by ilkarataev** [alryaz/hass-pandora-cas#7]
Работает на DX4G. Большое спасибо обязательно сделаю донат с зп)

**Comment by ilkarataev** [comment]
![image](https://user-images.githubusercontent.com/27670867/137719783-607de59f-4964-4ec9-af51-2ecec8f4bedd.png)

**Comment by alryaz** [comment]
@ilkarataev благодарю за Ваш вклад! Информация добавлена в README.
К слову, если Ваш автомобиль поддерживает TPMS/окошки ([проверить можно тут](https://loader.alarmtrade.ru)), напишите, пожалуйста, в этот же issue.
