### ISSUE TITLE
Добавить возможность выбора sim-карты для отображения баланса

### ISSUE THREAD

**Issue by Fonarik94** [alryaz/hass-pandora-cas#8]
Добавьте возможность выбора sim-карты для отображения баланса. 
Это актуально для охранных систем со встроенной sim-картой и sim-слотом (DXL-4790).
В Украине используется только sim-2, так как sim-1 - это Российский номер.

**Comment by alryaz** [comment]
Принял; будет добавлено, скорее всего, как множество сенсоров для доступных симок.
Ожидайте к v1.2.0.

**Comment by alryaz** [comment]
В грядущем обновлении два сенсора сим-карт. В master-ветке последние изменения.

**Comment by alryaz** [comment]
В обновлениях v2023.6.* добавлено
